// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH21GyDAvYcgvglkpwilfNPK_fZQ5mnAM',
    appId: '1:626241921837:web:2167274906f47b760b29a4',
    messagingSenderId: '626241921837',
    projectId: 'fruit-hub-afcae',
    authDomain: 'fruit-hub-afcae.firebaseapp.com',
    storageBucket: 'fruit-hub-afcae.firebasestorage.app',
    measurementId: 'G-CM3WY06HW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTg9JO5mp-Iz1zWm30ITES6BuQ8fnuvuA',
    appId: '1:626241921837:android:dcc1a557dc5025700b29a4',
    messagingSenderId: '626241921837',
    projectId: 'fruit-hub-afcae',
    storageBucket: 'fruit-hub-afcae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcB2_xk8rL3gQKu3GXG8jtB6WKsoNqn3Q',
    appId: '1:626241921837:ios:7b1bc8ca5c0f411c0b29a4',
    messagingSenderId: '626241921837',
    projectId: 'fruit-hub-afcae',
    storageBucket: 'fruit-hub-afcae.firebasestorage.app',
    androidClientId: '626241921837-np3lvfh5betdq5cf8dhg130sst8fphu1.apps.googleusercontent.com',
    iosClientId: '626241921837-rvs9jicaqrh6eime530v5f529r32o6fn.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcB2_xk8rL3gQKu3GXG8jtB6WKsoNqn3Q',
    appId: '1:626241921837:ios:7b1bc8ca5c0f411c0b29a4',
    messagingSenderId: '626241921837',
    projectId: 'fruit-hub-afcae',
    storageBucket: 'fruit-hub-afcae.firebasestorage.app',
    androidClientId: '626241921837-np3lvfh5betdq5cf8dhg130sst8fphu1.apps.googleusercontent.com',
    iosClientId: '626241921837-rvs9jicaqrh6eime530v5f529r32o6fn.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH21GyDAvYcgvglkpwilfNPK_fZQ5mnAM',
    appId: '1:626241921837:web:80603761ae7bd3010b29a4',
    messagingSenderId: '626241921837',
    projectId: 'fruit-hub-afcae',
    authDomain: 'fruit-hub-afcae.firebaseapp.com',
    storageBucket: 'fruit-hub-afcae.firebasestorage.app',
    measurementId: 'G-86EXKE0YWQ',
  );
}
